#RENAME TO appconfig.toml

# APP
app_name="NataliaNatalia"
app_version="0.5"
app_server_protocol="http"
app_server_host="localhost"
app_server_port=3001
app_setup_enabled=true
app_debug_mode=true
# CORS
app_CORS_Origins="http://localhost:4321,http://localhost:3001"
aPP_CORS_Headers="Origin, Content-Type, Accept"

# engines (sqlite / mysql / postgres)
[db.local]
    connName="local"
    engine="sqlite"
    host=""
    port=""
    user=""
    password=""
    dbname="./_db/mylocal"

